version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: it_user
      POSTGRES_PASSWORD: it_password
      POSTGRES_DB: itportal_db
    ports:
      - "5442:5432"
    volumes:
      - itportalv2_postgres_data:/var/lib/postgresql/data
      - ./backend/init:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      # Mount state file for persistence
      - ./backupec2_state.json:/app/backupec2_state.json
      # Mount raw data directory
      - ./raw-data:/app/raw-data
      - ../../secrets:/home/node/.ssh
      # - /home/jventures/.ssh:/home/node/.ssh

    environment:
      - NODE_ENV=production
      - AWS_PROFILE=aws_nonprod
      - AWS_REGION=ap-southeast-1
      - DATABASE_URL=postgresql://it_user:it_password@postgres:5442/itportal_db
    env_file:
      - .env
    # Check if we need to set user explicitly if UID mismatch causes permission issues
    # user: "${UID}:${GID}" 
    restart: unless-stopped

volumes:
  itportalv2_postgres_data:
